### ISSUE TITLE
https://ffmuc.net/stats/dashboard/db/node-graphite Falscher Titel bei Uptime

### ISSUE THREAD

**Issue by t-offline** [freifunkMUC/stats-tools#1]
Hallo,

der letzte graph sollte Uptime und nicht Clients im Titel haben.

Sonst prima und danke.

Servus
Christian

**Comment by fpletz** [comment]
Danke für den Hinweis, ist gefixt.

Das wird noch schöner gemacht, ist erstmal nur zum testen. :) Die Daten werden die nächsten Tage auch noch in die InfluxDB geschrieben.
